### ISSUE TITLE
Milestone 2 Feedback: Viz

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI_522_Group405#41]
For the second figure in the report, you should plot the price per night by eliminating the outliers, or else it is not informative. You can mention this elimination as a footnote to the plot or within your explanation as you have already done.

**Comment by ofer-m** [comment]
We did not remove outliers in our model, and we mentioned that in our report. Therefore, we are keeping the outliers in the plot. However, we are changing it to a boxplot instead of a histogram
